version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    env_file: .env
    volumes:
      - ./:/var/www
    networks:
      - pharmacy
    
  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    networks:
      - pharmacy

  # Database
  database:
    image: mysql:8.0.25
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $${database.default.database}
      MYSQL_ROOT_PASSWORD: $${database.default.password}
    ports:
      - "3307:3306"
    networks:
      - pharmacy

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./:/var/www
      - .env:/var/www/.env
    ports:
      - 80:80
    working_dir: /var/www
    profiles: ["npm"]
    entrypoint: ['npm']
    networks:
      - pharmacy

networks:
  pharmacy:
    name: "pharmacy-network"